name: prompter_hv12
version: 0.0.1
description: Library to create CLI wizards
author: Hector Vazquez <Hector_Vazquez@live.com>
homepage: https://www.linkedin.com/in/hector-vazquez-5774b899/

environment:
  sdk: '<3.0.0'